# Generated by Django 3.0.8 on 2020-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='images')),
                ('about', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
