# Generated by Django 3.0.8 on 2020-09-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfconvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
